use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;

const API_URL: &str = "https://ciphersuite.info/api/cs/";
const CACERT_URL: &str = "https://curl.se/ca/cacert.pem";

#[derive(Debug, Deserialize)]
struct ApiResponse {
    ciphersuites: Vec<BTreeMap<String, RawSuite>>,
}

#[derive(Debug, Deserialize)]
struct RawSuite {
    #[serde(default)]
    gnutls_name: String,
    #[serde(default)]
    openssl_name: String,
    hex_byte_1: String,
    hex_byte_2: String,
    #[serde(default)]
    protocol_version: String,
    #[serde(default)]
    kex_algorithm: String,
    #[serde(default)]
    auth_algorithm: String,
    #[serde(default)]
    enc_algorithm: String,
    #[serde(default)]
    hash_algorithm: String,
    security: String,
    #[serde(default)]
    tls_version: Vec<String>,
}

fn parse_hex_byte(s: &str) -> u8 {
    let t = s.trim_start_matches("0x").trim_start_matches("0X");
    u8::from_str_radix(t, 16).unwrap_or_else(|e| panic!("bad hex byte {s:?}: {e}"))
}

fn security_variant(s: &str) -> &'static str {
    match s {
        "recommended" => "Security::Recommended",
        "secure" => "Security::Secure",
        "weak" => "Security::Weak",
        "insecure" => "Security::Insecure",
        other => panic!("unknown security level from API: {other:?}"),
    }
}

fn tls_version_variant(s: &str) -> Option<&'static str> {
    match s {
        "SSL2.0" | "SSL2" => Some("TlsVersion::Ssl20"),
        "SSL3.0" | "SSL3" => Some("TlsVersion::Ssl30"),
        "TLS1.0" => Some("TlsVersion::Tls10"),
        "TLS1.1" => Some("TlsVersion::Tls11"),
        "TLS1.2" => Some("TlsVersion::Tls12"),
        "TLS1.3" => Some("TlsVersion::Tls13"),
        "" => None,
        other => panic!("unknown tls_version from API: {other:?}"),
    }
}

fn rust_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            c if c.is_ascii_graphic() || c == ' ' => out.push(c),
            c => out.push_str(&format!("\\u{{{:x}}}", c as u32)),
        }
    }
    out.push('"');
    out
}

fn fetch_cacert(out_dir: &Path) {
    println!("cargo:rerun-if-env-changed=CACERT_URL");

    let url = env::var("CACERT_URL").unwrap_or_else(|_| CACERT_URL.to_string());
    let body = ureq::get(&url)
        .header("User-Agent", "tls-scanner-build/0.1 (+build.rs)")
        .call()
        .unwrap_or_else(|e| panic!("failed to fetch {url}: {e}"))
        .into_body()
        .read_to_string()
        .expect("failed to read cacert response body");

    assert!(
        body.contains("-----BEGIN CERTIFICATE-----"),
        "downloaded cacert.pem looks malformed (no PEM block found)"
    );

    fs::write(out_dir.join("cacert.pem"), body.as_bytes())
        .expect("failed to write cacert.pem to OUT_DIR");
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CIPHERSUITE_API_URL");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    fs::create_dir_all(&out_dir).ok();

    fetch_cacert(&out_dir);

    let url = env::var("CIPHERSUITE_API_URL").unwrap_or_else(|_| API_URL.to_string());

    let body = ureq::get(&url)
        .header("User-Agent", "tls-scanner-build/0.1 (+build.rs)")
        .header("Accept", "application/json")
        .call()
        .unwrap_or_else(|e| panic!("failed to fetch {url}: {e}"))
        .into_body()
        .read_to_string()
        .expect("failed to read API response body");

    let parsed: ApiResponse =
        serde_json::from_str(&body).expect("API returned unexpected JSON shape");

    let mut suites: Vec<(u16, String, RawSuite)> = parsed
        .ciphersuites
        .into_iter()
        .flat_map(|m| m.into_iter())
        .map(|(name, raw)| {
            let b1 = parse_hex_byte(&raw.hex_byte_1);
            let b2 = parse_hex_byte(&raw.hex_byte_2);
            let code = (u16::from(b1) << 8) | u16::from(b2);
            (code, name, raw)
        })
        .collect();
    suites.sort_by_key(|(code, name, _)| (*code, name.clone()));

    assert!(!suites.is_empty(), "API returned zero cipher suites");

    {
        let mut seen = std::collections::HashSet::new();
        for (code, name, _) in &suites {
            if !seen.insert(*code) {
                eprintln!("warning: duplicate cipher code 0x{code:04x} ({name})");
            }
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs from https://ciphersuite.info/api/cs/\n");
    out.push_str("#![allow(dead_code)]\n");
    out.push_str("use super::{CipherSuite, Security, TlsVersion};\n\n");
    out.push_str(&format!("pub const COUNT: usize = {};\n\n", suites.len()));

    out.push_str("pub static ALL: &[CipherSuite] = &[\n");
    for (code, name, r) in &suites {
        let versions: Vec<&'static str> = r
            .tls_version
            .iter()
            .filter_map(|v| tls_version_variant(v))
            .collect();
        let versions_lit = if versions.is_empty() {
            "&[]".to_string()
        } else {
            format!("&[{}]", versions.join(", "))
        };
        out.push_str(&format!(
            "    CipherSuite {{\n\
             \x20       code: 0x{code:04x},\n\
             \x20       iana_name: {name},\n\
             \x20       openssl_name: {openssl},\n\
             \x20       gnutls_name: {gnutls},\n\
             \x20       protocol_version: {proto},\n\
             \x20       kex_algorithm: {kex},\n\
             \x20       auth_algorithm: {auth},\n\
             \x20       enc_algorithm: {enc},\n\
             \x20       hash_algorithm: {hash},\n\
             \x20       security: {sec},\n\
             \x20       tls_versions: {versions_lit},\n\
             \x20   }},\n",
            code = code,
            name = rust_str(name),
            openssl = rust_str(&r.openssl_name),
            gnutls = rust_str(&r.gnutls_name),
            proto = rust_str(&r.protocol_version),
            kex = rust_str(&r.kex_algorithm),
            auth = rust_str(&r.auth_algorithm),
            enc = rust_str(&r.enc_algorithm),
            hash = rust_str(&r.hash_algorithm),
            sec = security_variant(&r.security),
            versions_lit = versions_lit,
        ));
    }
    out.push_str("];\n\n");

    // -- phf map: code -> index into ALL
    // -- phf map: code -> index into ALL
    {
        let mut m = phf_codegen::Map::<u16>::new();
        let owned: Vec<String> = (0..suites.len()).map(|i| i.to_string()).collect();
        for ((code, _, _), v) in suites.iter().zip(owned.iter()) {
            m.entry(*code, v);
        }
        out.push_str("pub static BY_CODE: phf::Map<u16, usize> = ");
        out.push_str(&m.build().to_string());
        out.push_str(";\n\n");
    }

    // -- phf map: iana name -> index
    {
        let mut m = phf_codegen::Map::<&str>::new();
        let owned: Vec<(String, String)> = suites
            .iter()
            .enumerate()
            .map(|(idx, (_, name, _))| (name.clone(), idx.to_string()))
            .collect();
        for (k, v) in &owned {
            m.entry(k.as_str(), v);
        }
        out.push_str("pub static BY_NAME: phf::Map<&'static str, usize> = ");
        out.push_str(&m.build().to_string());
        out.push_str(";\n\n");
    }

    let versions = [
        ("SSL20", "Ssl20"),
        ("SSL30", "Ssl30"),
        ("TLS10", "Tls10"),
        ("TLS11", "Tls11"),
        ("TLS12", "Tls12"),
        ("TLS13", "Tls13"),
    ];
    for (const_name, variant) in versions {
        let idxs: Vec<usize> = suites
            .iter()
            .enumerate()
            .filter_map(|(i, (_, _, r))| {
                let has = r
                    .tls_version
                    .iter()
                    .filter_map(|v| tls_version_variant(v))
                    .any(|v| v == format!("TlsVersion::{variant}"));
                if has { Some(i) } else { None }
            })
            .collect();
        out.push_str(&format!(
            "pub static INDICES_{const_name}: &[usize] = &{idxs:?};\n\n"
        ));
    }

    for (label, variant) in [
        ("RECOMMENDED", "recommended"),
        ("SECURE", "secure"),
        ("WEAK", "weak"),
        ("INSECURE", "insecure"),
    ] {
        let idxs: Vec<usize> = suites
            .iter()
            .enumerate()
            .filter_map(|(i, (_, _, r))| (r.security == variant).then_some(i))
            .collect();
        out.push_str(&format!(
            "pub static INDICES_{label}: &[usize] = &{idxs:?};\n\n"
        ));
    }

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR not set"));
    fs::create_dir_all(&out_dir).ok();
    fs::write(out_dir.join("ciphers_generated.rs"), &out)
        .expect("failed to write generated file to OUT_DIR");

    let src_path = PathBuf::from("src/scanner/tls/ciphers.rs");
    fs::create_dir_all(src_path.parent().unwrap()).ok();
    // Only rewrite if changed -- keeps mtime stable and avoids fighting rust-analyzer.
    let prev = fs::read_to_string(&src_path).unwrap_or_default();
    if prev != out {
        fs::write(&src_path, &out).expect("failed to write src/tls/ciphers.rs");
    }
}
